[build]
  base = "client"
  publish = "dist/spa"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[dev]
  targetPort = 8080