[build]
  base = "."                   # Root of your repo
  publish = "dist/spa"         # Folder with your static build output
  command = "pnpm run build"   # Use pnpm to build, since you use pnpm locally

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  targetPort = 8080